kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Python
    image: python:3.9
    commands:
      - ln -fs .env.development .env
      - pip install -r requirements.txt
      - pip install -r requirements-test.txt
      - flake8
      - mypy app --ignore-missing-imports --strict
      - coverage run -m unittest discover
      - coverage report -m

  - name: Test Node
    image: node:16
    commands:
      - apt-get update && apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libcups2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxss1 libxtst6 lsb-release xdg-utils
      - ln -fs .env.development .env
      - npm ci
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.development .env
      - shellcheck -x bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=SC2046 --ignore=SC2006

  - name: Build Docker Container
    depends_on:
      - Test Python
      - Test Node
      - Test Bash
      - Test Dockerfile
    image: plugins/docker:19
    settings:
      repo: chase-center-calendar
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh:1.6.3
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/chase-center-calendar/bin/deploy.sh master"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master
