kind: pipeline
type: docker
name: test

volumes:
  - name: ssh_key
    host:
      path: /home/albertyw/.ssh/id_ed25519

steps:
  - name: Test Python
    image: python:3.10
    commands:
      - ln -fs .env.development .env
      - pip install -r requirements.txt
      - pip install -r requirements-test.txt
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - flake8
      - mypy . --ignore-missing-imports --strict
      - cc-test-reporter before-build
      - coverage run -m unittest discover
      - exitcode="$?"
      - coverage report -m
      - coverage xml -i
      - cc-test-reporter after-build --exit-code "$exitcode"
    environment:
      CC_TEST_REPORTER_ID: 2fd1548c4a64215b1a8790e4cf423b329dda550bcf437b5e5835c16fd0da332b

  - name: Test Node
    image: satantime/puppeteer-node:18-bullseye-slim
    commands:
      - ln -fs .env.development .env
      - npm ci
      - npm test

  - name: Test Bash
    image: koalaman/shellcheck-alpine:stable
    commands:
      - ln -fs .env.development .env
      - shellcheck -x bin/*.sh

  - name: Test Dockerfile
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile --ignore=DL3008 --ignore=SC2046 --ignore=SC2006

  - name: Test Nginx
    image: yandex/gixy:0.1.20
    commands:
      - gixy config/nginx/*

  - name: Build Docker Container
    depends_on:
      - Test Python
      - Test Node
      - Test Bash
      - Test Dockerfile
      - Test Nginx
    image: plugins/docker:20
    settings:
      repo: chase-center-calendar
      tags: test
      dry_run: true

  - name: Deploy
    depends_on:
      - Build Docker Container
    image: appleboy/drone-ssh:1.6.3
    settings:
      host: direct.albertyw.com
      username: albertyw
      key_path: /root/ssh/id_ed25519
      script:
        - "/home/albertyw/chase-center-calendar/bin/deploy.sh master"
    volumes:
      - name: ssh_key
        path: /root/ssh/id_ed25519
    when:
      branch:
        - master
